### ISSUE TITLE
Mutations with one optional argument inside object can fail

### ISSUE THREAD

**Issue by Floriferous** [cult-of-coders/mutations#6]
If I define a mutation like this:

```js
export const doSomething = new Mutation({
  name: 'doSomething',
  params: {
    myParam: Match.Optional(String),
  },
});
```

And later on decide to call it like this: `doSomething.run()`, without an empty object, it fails, because `check` expects at least an object: `doSomething.run({})`.

Could we pass an empty object by default to `run`? https://github.com/cult-of-coders/mutations/blob/7f82b54c149881d7175c439b877601b412db4eb9/lib/mutation.class.js#L92

Change it to this: `run(callParams = {}, options = {}) {` since this library enforces the use of a single params objects anyways?

**Comment by theodorDiaconu** [comment]
callParams = {} is good approach
