### ISSUE TITLE
Make mutations ran on the server return the result, and not a promise

### ISSUE THREAD

**Issue by Floriferous** [cult-of-coders/mutations#7]
It appears that running a mutation from the server also returns a promise, and not the synchronous result of the meteor method. Is this by design, or could it be possible to make them behave the same way meteor's original methods work?

This doesn't work on the server:
`const todoId = insertTodo.run({ ... })`

**Comment by theodorDiaconu** [comment]
This is by design. To always use promises, it's by far more elegant.

You could do:
```
const todoId = await insertTodo.run({...})
```
